spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:finance_tracker}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:abwx}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,metrics,caches
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.secret=finance-tracker-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000
jwt.refresh-expiration=2592000000