apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-tracker
  namespace: finance-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-tracker
  template:
    metadata:
      labels:
        app: finance-tracker
    spec:
      containers:
        - name: finance-tracker
          image: finance-tracker:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: finance-config
            - secretRef:
                name: finance-secrets
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
              ephemeral-storage: 256Mi
            limits:
              memory: 512Mi
              ephemeral-storage: 1Gi
      automountServiceAccountToken: false
