apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-config
  namespace: finance-tracker
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: finance_tracker
  DB_USERNAME: admin
  REDIS_HOST: redis